#include "hacs_platform.h"
#include "hacs_pstore_layout.h"

const uint32_t hacs_pstore_ent_rel_addr[HACS_PSTORE_NUM_ENTRIES] = {
  [HACS_PSTORE_MAG_HARD_CAL] = PSTORE_MAG_HARD_CAL_ADDR,
  [HACS_PSTORE_MAG_SOFT_CAL] = PSTORE_MAG_SOFT_CAL_ADDR,
  [HACS_PSTORE_BARO_REF_CAL] = PSTORE_BARO_GND_REF_ADDR,
  [HACS_PSTORE_AIRSPEED_ZERO_CAL] = PSTORE_AIRSPD_OFFSET_ADDR,
};

const uint16_t hacs_pstore_ent_size[HACS_PSTORE_NUM_ENTRIES] = {
  [HACS_PSTORE_MAG_HARD_CAL] = PSTORE_MAG_HARD_CAL_LEN,
  [HACS_PSTORE_MAG_SOFT_CAL] = PSTORE_MAG_SOFT_CAL_LEN,
  [HACS_PSTORE_BARO_REF_CAL] = PSTORE_BARO_GND_REF_LEN,
  [HACS_PSTORE_AIRSPEED_ZERO_CAL] = PSTORE_AIRSPD_OFFSET_LEN,
};
