#ifndef _HACS_ERROR_CODES_H_
#define _HACS_ERROR_CODES_H_

typedef enum {
  HACS_NO_ERROR = 0,

  HACS_NRF24_TX_FAILED,
  HACS_NRF24_RX_INVALID_LENGTH,
  HACS_NRF24_RX_NOT_READY,

  HACS_EXTI_OVERWRITE_WARN,

  HACS_GPS_FORMAT_NOT_SUPPORTED,

  HACS_ERR_ALREADY_IN_USE,

  HACS_CAL_INVALID,

} hacs_error_t;

#endif
